<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Version.props" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);build/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.0" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/app-icon.png" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests/**/*.cs" />
  </ItemGroup>
</Project>
